# Generated by Django 2.1.3 on 2018-11-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181114_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='ambulance_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='dashboard.Ambulance'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hospital_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='dashboard.Hospital'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='dashboard.Patient'),
        ),
    ]
