# Generated by Django 2.1.3 on 2018-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181119_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
