# Generated by Django 2.1.3 on 2018-11-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181120_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='on_trip',
            field=models.BooleanField(default=True),
        ),
    ]
